import CardsRenderer from "../components/CardsRenderer";
import Form from "../components/Form";
import useFetch from "../hooks/useFetch";

const Home = () => {
  const {loading, data, searchText, setSearchText, error} = useFetch("");


  return (
    <section className="container">
      <div>
        <h1 className="text-4xl">Display Showcase</h1>
        <p className="my-2 text-base max-w-[500px]">Explore the world of images generated by DALL-E AI</p>
      </div>

      <div className="mt-16">
        <Form />
      </div>

      <div className="mt-10">
        {loading ? 
          (<p>Loading</p>) :
          (<>
            {searchText && (<h3>Results for {searchText}</h3>)}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? 
                (<CardsRenderer data={[1, 2, 3]} title="No search results found"/>)  :
                (<CardsRenderer data={[]} title="No images found"/>)
              }
            </div>
          </>)
        }
      </div>
    </section>
  );
}

export default Home